### ISSUE TITLE
THE TOWER – Superposición de personaje y enemigo (V 0.11)

### ISSUE THREAD

**Issue by ZoeCamos** [niketso/TheTower#11]
Descripción:

Cuando un enemigo ataca al personaje y este muere, el PJ se superpone con el enemigo.

Reproducción rate: -
	
Pasos: 
-Subir a los pisos superiores.
-Dejar que el enemigo ataque al personaje mientras este camina.

Resultado esperado: Que el personaje no se superponga con el enemigo.

Resultado obtenido: El PJ se superpone.

Windows 10
Resolución: 1920x1080, High Quality.

![pj superpuesto](https://user-images.githubusercontent.com/45185546/48863381-ea3d3000-eda7-11e8-9576-edc0e0a871ee.gif)

**Comment by niketso** [comment]
Duplicado con #18
