### ISSUE TITLE
THE TOWER – Personaje queda congelado en el lugar (V 0.12)

### ISSUE THREAD

**Issue by ZoeCamos** [niketso/TheTower#12]
Descripción:

1º caso: Si el personaje es atacado al mismo tiempo por dos enemigos pierde directamente dos vidas. Luego de que el personaje revive, si sube al piso superior quedará congelado en el lugar (con la animación de caminar) sin posibilidad de realizar alguna acción.

2ºcaso: Si el personaje pierde una vida en el 3º piso en adelante, y luego de revivir sube al siguiente piso, quedará congelado en el lugar (con la animación de caminar) sin posibilidad de realizar alguna acción.

Reproducción rate: 100%

Pasos 1º caso:
-Subir a uno de los pisos superiores.
-Dejar que el personaje sea atacado por dos enemigos al mismo tiempo.
-Volver a subir al piso superior.

Pasos 2º caso:
-Subir al tercer piso o pisos superiores.
-Dejar que el personaje pierda una vida.
-Volver a subir al piso superior.

Resultado esperado: Que el personaje, al subir, pueda moverse libremente.

Resultado obtenido: El personaje queda congelado en el lugar, sin posibilidad de hacer algo.

Windows 10
Resolución: 1920x1080, High Quality.

**Comment by niketso** [comment]
Bug solucionado, próximo a publicar en versión 0.13
