### ISSUE TITLE
THE TOWER – Personaje pierde dos vidas al mismo tiempo y reaparece con torreta (V 0.11)

### ISSUE THREAD

**Issue by ZoeCamos** [niketso/TheTower#2]
Descripción:
Luego de que el personaje muere atacado por dos enemigos al mismo tiempo, este pierde dos vidas y  reaparece al principio junto con una torreta.

Reproducción rate: 100%	

Pasos: 
-Subir a uno de los pisos superiores.
-Dejar que el personaje sea atacado por dos enemigos al mismo tiempo.  

Resultado esperado: Que el PJ pierda una sola vida y reaparezca sin torreta.

Resultado obtenido: El PJ pierde dos vidas y una torreta aparece al principio.

Windows 10
Resolución: 1920x1080, High Quality

![2-vidas-y-torreta-al-principio](https://user-images.githubusercontent.com/45185546/48860063-a134ae00-ed9e-11e8-869b-0ebe71a6868c.gif)

**Comment by niketso** [comment]
Cerrado con #12
