### ISSUE TITLE
THE TOWER – Enemigos caen sobre el personaje (V 0.12)

### ISSUE THREAD

**Issue by ZoeCamos** [niketso/TheTower#20]
Descripción:

Si el personaje muere en pisos superiores y quedan varios enemigos, estos irán siguiendo al PJ y cayendo. Los enemigos pueden caer sobre el personaje y el resto no atacará.

Reproducción rate: 100%

Pasos:
-Subir a uno de los pisos superiores.
-Dejar morir al PJ.
-Quedarse en el primer piso.

Resultado esperado: Que los enemigos queden en sus respectivos pisos – Que los enemigos caigan al lado del PJ.

Resultado obtenido: Los enemigos comienzan a caer hacia pisos inferiores (siguiendo al PJ) – Los enemigos caen sobre el PJ.

Windows 10
Resolución: 1920x1080, High Quality.

![enemigos sobre pj 0 12](https://user-images.githubusercontent.com/45185546/48875003-14f1ad80-edd5-11e8-9936-73729e203082.png)

**Comment by niketso** [comment]
Se resuelve en #15
