### ISSUE TITLE
THE TOWER – Enemigos caen de pisos superiores (V 0.11)

### ISSUE THREAD

**Issue by ZoeCamos** [niketso/TheTower#3]
Descripción:

Los enemigos que se encuentran en los pisos superiores comienzan a caer a donde se encuentra en personaje (siguen los movimientos del PJ).

Reproducción rate: 100%	

Pasos: 
-Subir a uno de los pisos superiores.
-Dejar morir al PJ.
-Quedarse en el primer piso.  

Resultado esperado: Que los enemigos queden en sus respectivos pisos (que choquen contra la pared)

Resultado obtenido: Los enemigos comienzan a caer hacia pisos inferiores (siguiendo al PJ).

Windows 10
Resolución: 1920x1080, High Quality

![enemigos-caen-de-pisos-superiores](https://user-images.githubusercontent.com/45185546/48861045-56686580-eda1-11e8-9c95-2b476b81a7f0.gif)

**Comment by niketso** [comment]
Cerrado con #15
