### ISSUE TITLE
THE TOWER – Enemigos caen sobre el personaje (V 0.11)

### ISSUE THREAD

**Issue by ZoeCamos** [niketso/TheTower#5]
Descripción:

Si el personaje muere en pisos superiores y quedan varios enemigos, estos irán siguiendo al PJ y cayendo. Los enemigos pueden caer sobre el personaje y el resto no atacará.

Reproducción rate: 100%	

Pasos: 
-Subir a uno de los pisos superiores.
-Dejar morir al PJ.
-Quedarse en el primer piso.

Resultado esperado: Que los enemigos queden en sus respectivos pisos – Que los enemigos caigan al lado del PJ.

Resultado obtenido: Los enemigos comienzan a caer hacia pisos inferiores (siguiendo al PJ) – Los enemigos caen sobre el PJ.

Windows 10
Resolución: 1920x1080, High Quality.

![enemigos sobre pj](https://user-images.githubusercontent.com/45185546/48861457-5d43a800-eda2-11e8-9804-46f2effe7f13.png)

**Comment by niketso** [comment]
Este error es consecuencia del error #15
