### ISSUE TITLE
 THE TOWER – Atacar detiene la carga del dash (V 0.11)

### ISSUE THREAD

**Issue by ZoeCamos** [niketso/TheTower#6]
Descripción:

Si el personaje ataca mientras el dash está cargando, esta se detendrá por un instante.

Reproducción rate: 100%	

Pasos: 
-Utilizar el dash.
-Atacar mientras el dash está recargando.

Resultado esperado: El dash continúa recargando mientras el personaje ataca.

Resultado obtenido: La carga de dash se detiene mientras el personaje ataca.

Windows 10
Resolución: 1920x1080, High Quality.

![ataque-detiene-carga-dash](https://user-images.githubusercontent.com/45185546/48861761-2e7a0180-eda3-11e8-9c71-c6b46ade1232.gif)

**Comment by niketso** [comment]
Solucionado en #14 falta implementar
