### ISSUE TITLE
THE TOWER – Se congela el juego al salir al menú y volver a entrar (V 0.11)

### ISSUE THREAD

**Issue by ZoeCamos** [niketso/TheTower#7]
Descripción:

Durante el juego: si uno decide pausar el juego, salir al menú y volver a jugar la imagen del juego quedará congelada (sin responder a los controles). La única manera de arreglarlo es utilizar la tecla “Esc”.

Reproducción rate: 100%	

Pasos: 
-Comenzar el juego.
-Pausar y salir al menú.
-Volver a entrar al juego.

Resultado esperado: Que se pueda comenzar a jugar inmediatamente sin que la imagen se congele.

Resultado obtenido: La imagen se congela al volver al juego.

Windows 10
Resolución: 1920x1080, High Quality

![salir-y-volver-a-entrar-al-juego-congela](https://user-images.githubusercontent.com/45185546/48862023-d55e9d80-eda3-11e8-83d4-874856527c41.gif)

**Comment by niketso** [comment]
Este bug fue solucionado en la versión 0.12
