### ISSUE TITLE
THE TOWER – Cartel “Press C” del segundo piso fuera del lugar (V 0.11)

### ISSUE THREAD

**Issue by ZoeCamos** [niketso/TheTower#8]
Descripción:

El cartel “Press C” del segundo piso aparece alejado del ascensor (a diferencia de los demás ascensores), quedando fuera de visión.

Resultado esperado: Que el cartel “Press C” quede centrado con el ascensor como el resto.

Resultado obtenido: El cartel queda fuera del ascensor.

Windows 10
Resolución: 1920x1080, High Quality.

![press c ascensor](https://user-images.githubusercontent.com/45185546/48862230-76e5ef00-eda4-11e8-8e44-fd39a9cd28dd.png)

**Comment by Lithiot** [comment]
Duplicado a solucionar en #19
