### ISSUE TITLE
THE TOWER – Personaje queda congelado en el lugar (V 0.11)

### ISSUE THREAD

**Issue by ZoeCamos** [niketso/TheTower#9]
Descripción:

Primero se debe reproducir el bug “Personaje pierde dos vidas al mismo tiempo y reaparece con torreta” (Subir a uno de los pisos superiores, dejar que el personaje sea atacado por dos enemigos al mismo tiempo).
Luego de que el personaje revive, si sube al piso superior quedará congelado en el lugar (con la animación de caminar) sin posibilidad de realizar alguna acción.

Reproducción rate: 100%	

Pasos: 
-Subir a uno de los pisos superiores.
-Dejar que el personaje sea atacado por dos enemigos al mismo tiempo.
-Volver a subir al piso superior.  

Resultado esperado: Que el personaje, al subir, pueda moverse libremente.

Resultado obtenido: El personaje queda congelado en el lugar, sin posibilidad de hacer algo.

Windows 10
Resolución: 1920x1080, High Quality.

![pj-queda-trabado](https://user-images.githubusercontent.com/45185546/48862434-228f3f00-eda5-11e8-9b3a-c72a5767fb3e.gif)

**Comment by niketso** [comment]
Se soluciono en el #12
